development: &default
  host: localhost
  adapter: postgresql
  database: login_db
  username: postgres
  password: postgres
  pool: 30
  timeout: 5000
  gssencmode: disable


test:
  <<: *default
  database: login_test_db

production: &production
  <<: *default
  hots: localhost